export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL"; 
export const LOGOUT = "LOGOUT"
// export const CLEAR_PROFILE = "CLEAR_PROFILE"

export const GET_PRODUCT = "GET_PRODUCT";
export const FAILED_PRODUCT = "FAILED_PRODUCT";

export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const DECREMENT_CART_ITEM_QUANTITY = "DECREMENT_CART_ITEM_QUANTITY";
export const INCREMENT_CART_ITEM_QUANTITY = "INCREMENT_CART_ITEM_QUANTITY";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
export const CLEAR_CART  = "CLEAR_CART"
export const CHECKOUT = "CHECKOUT"
export const CHECKOUT_FAILED = "CHECKOUT_FAILED"

export const MODAL_OPEN = "MODAL_OPEN";
export const MODAL_CLOSE = "MODAL_CLOSE";

export const SEE_DETAILS = "SEE_DETAILS";
